


MeasureHeader = [
  'No',
  'Pixels in Area',
  'X Center of Gravity',
  'Y Center of Gravity',
  'Min X in Area',
  'Max X in Area',
  'Min Y in Area',
  'Max Y in Area',
  'Area Width',
  'Area Height',
  'Inverse Flattening Rate',
  'Short Side Length',
  'Long Side Length',
  'Oblateness',
  'Roundness',
  'Ellipsity',
  'Rectangular Filling Ratio',
  'Outer Pixels',
  'Average Thickness',
  'Slenderness',
  'Wrap count',
  'Outer Area',
  'Degree of Short Side Direction',
  'Degree of Long Side Direction',
  'Average Pixel Value of Area',
  'Minimum Pixel Value of Area',
  'Maximum Pixel Value of Area',
  'Internal Contrast',
  'Average Pixel Value of External Area',
  'Contrast of Inner & External Area',
  'Internal Contrast',
  'Angle-Angle',
  'Angle-Center X Coordinate',
  'Angle-Center Y Coordinate',
  'Angle-Radius',
  'BestFit-Max Distance',
  'BestFit-Mean Distance',
  'BestFit-Min Distance',
  'BestFit-RMSE',
  'Line-Angle',
  'Line-Arc Angle',
  'Line-Arc Center X',
  'Line-Arc Center Y',
  'Line-Arc Radius',
  'Line-Chord Length',
  'Line-End X',
  'Line-End Y',
  'Line-End XY',
  'Line-Length',
  'Line-Position X',
  'Line-Position XY',
  'Line-Position Y',
  'Line-Start X',
  'Line-Start XY',
  'Line-Start Y',
  'Object-Class',
  'Object-Class Name',
  'Object-Parent',
  'Point-Intensity',
  'Point-Location X',
  'Point-Location XY',
  'Point-Location Y',
  'Region-Area',
  'Region-Axis,Major',
  'Region-Axis,Minor',
  'Region-Centroid X',
  'Region-Centroid XY',
  'Region-Centroid Y',
  'Region-Direction',
  'Region-Intensity, Mean',
  'Region-Percent Area Parent',
  'Region-Perimeter,Bounding Polygon',
]